version: '3'

services:
  app:
    build: .
    ports:
      - "3001:3001"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/streamingapp
      - NODE_ENV=production
    depends_on:
      - mongo
    volumes:
      - ./src:/usr/src/app/src
      - ./logs:/usr/src/app/logs

  mongo:
    image: mongo:4.4
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo-data: